version: "5"

services:
  db:
    image: "postgres:14.3"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test5b
      POSTGRES_DB: db5b
    container_name: webapi-5b
    volumes:
      - ./postgres:/var/lib/postgresql/data
